# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print(np.__version__)
np.show_config()


1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/pieri/anaconda3/Library/include
    lib directory: C:/Users/pieri/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]

# Using random.randint
a=np.random.randint(100,size=(2,3,5))

# Using random.random
a1=np.random.random(size=(2,3,5))

# Using random.uniform
a2=np.random.uniform(100,size=(2,3,5))


### 4. Print a.


In [4]:
### [your code here]
print(a)


[[[23 41 20 98 76]
  [97 11  9 47 91]
  [23  5 29 53 91]]

 [[25 70 73 70 97]
  [77 65 63 55 32]
  [76  2  8 63 19]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
### [your code here]
b=np.ones((5,2,3))



### 6. Print b.


In [6]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
### [your code here]
if a.size==b.size:
    print('a and b have the same size:',a.size)
else:
    print('a size is ',a.size,' and size b is ',b.size)

a and b have the same size: 30



### 8. Are you able to add a and b? Why or why not?


In [8]:
### [your code here]
sum=a+b
#You can not because they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
### [your code here]
c=np.transpose(b,(1,2,0))


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [10]:
### [your code here]
d=a+c
#When used the function transpose(), its possible to rearrange the shape. So was possible to sum them bc now c and d have the same shape.


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [11]:
### [your code here]
print('Array a:\n',a)
print('\nArray d:\n',d)
#Because b was an array only with one, d is an array that is equal to a+1

Array a:
 [[[23 41 20 98 76]
  [97 11  9 47 91]
  [23  5 29 53 91]]

 [[25 70 73 70 97]
  [77 65 63 55 32]
  [76  2  8 63 19]]]

Array d:
 [[[24. 42. 21. 99. 77.]
  [98. 12. 10. 48. 92.]
  [24.  6. 30. 54. 92.]]

 [[26. 71. 74. 71. 98.]
  [78. 66. 64. 56. 33.]
  [77.  3.  9. 64. 20.]]]



### 12. Multiply a and c. Assign the result to e.


In [12]:
### [your code here]
e=a*c



### 13. Does e equal to a? Why or why not?


In [13]:
### [your code here]
print('Array a:\n',a)
print('\nArray e:\n',e)
# Because array c has only values=1, when you multiplicate a and c, is the same as a*1 
# so a and e are the same


Array a:
 [[[23 41 20 98 76]
  [97 11  9 47 91]
  [23  5 29 53 91]]

 [[25 70 73 70 97]
  [77 65 63 55 32]
  [76  2  8 63 19]]]

Array e:
 [[[23. 41. 20. 98. 76.]
  [97. 11.  9. 47. 91.]
  [23.  5. 29. 53. 91.]]

 [[25. 70. 73. 70. 97.]
  [77. 65. 63. 55. 32.]
  [76.  2.  8. 63. 19.]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [14]:
### [your code here]
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [15]:
### [your code here]
f=np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [16]:
### [your code here]
cond_25=(d>d_min) & (d<d_mean)
cond_75=(d>d_mean) & (d<d_max)
cond_50=d==d_mean
cond_0=d==d_min
cond_100=d==d_max

f[cond_25]=25
f[cond_75]=75
f[cond_50]=50
f[cond_0]=0
f[cond_100]=100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [17]:
### [your code here]
print('Array d:\n',d)
print('\nArray f:\n',f)

Array d:
 [[[24. 42. 21. 99. 77.]
  [98. 12. 10. 48. 92.]
  [24.  6. 30. 54. 92.]]

 [[26. 71. 74. 71. 98.]
  [78. 66. 64. 56. 33.]
  [77.  3.  9. 64. 20.]]]

Array f:
 [[[ 25.  25.  25. 100.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 25.  25.  25.  75.  75.]]

 [[ 25.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  25.]
  [ 75.   0.  25.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [18]:
### [your code here]
st=np.empty((2,3,5),dtype=object)
st[cond_25]='B'
st[cond_75]='D'
st[cond_50]='C'
st[cond_0]='A'
st[cond_100]='E'
print(st)

[[['B' 'B' 'B' 'E' 'D']
  ['D' 'B' 'B' 'B' 'D']
  ['B' 'B' 'B' 'D' 'D']]

 [['B' 'D' 'D' 'D' 'D']
  ['D' 'D' 'D' 'D' 'B']
  ['D' 'A' 'B' 'D' 'B']]]
